### ISSUE TITLE
[Item export - 3.16] Add new stat ranges for armors

### ISSUE THREAD

**Issue by Journeytojah** [Project-Path-of-Exile-Wiki/PyPoE#29]
We need to update base types to the new system.

```22:18:59 Traceback (most recent call last):
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\exporter\wiki\handler.py", line 286, in wrapper     
    result = func(parser, pargs, *args, **kwargs)
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\exporter\wiki\parsers\item.py", line 3548, in by_rowid
    return self._export(
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\exporter\wiki\parsers\item.py", line 3725, in _export
    if not f(self, infobox, base_item_type):
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\exporter\wiki\parsers\item.py", line 86, in func    
    _apply_column_map(infobox, data_mapping, data)
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\cli\exporter\wiki\parsers\item.py", line 61, in _apply_column_map
    value = list_object[k]
  File "c:\users\journey\desktop\dev\poe-tools\wiki-fork\pypoe\PyPoE\poe\file\dat.py", line 407, in __getitem__
    raise KeyError(item)
KeyError: 'Armour'

**Comment by angelic-knight** [comment]
Started (perhaps finished the PyPoE side) work on this.
You can see changes I made in [my fork](https://github.com/angelic-knight/PyPoE/commit/78214dc2f69b75c0f31c5a0c32967f1db57307ad?diff=split#diff-e670fb1cd829f387081b537c6f68eb9ae328f418ffd8e8786176799e76788595)

It seems to work ok, spitting things out like this:
![image](https://user-images.githubusercontent.com/89628672/139790396-bec50ef2-dfa9-4b05-a84b-8d7e51a3a28b.png)

I have not made changes on the wiki to support this.
We probably want to add a new value for average armour/evasion/energy shield/ward for easy sorting, at least on the wiki.

**Comment by angelic-knight** [comment]
Closing as this is complete.
